name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# From https://github.com/arcium-hq/setup-arcium
jobs:
  run-arcium-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arcium-hq/setup-arcium@v0.3.0
        with:
          runner-arch-os: x86_64_linux
      - run: arcium build
        shell: bash