name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup Rust 1.88.0
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.88.0

      - name: Setup Solana and Anchor
        uses: metadaoproject/setup-anchor@main

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Install Arcium CLI
        run: curl --proto '=https' --tlsv1.2 -sSfL https://install.arcium.com/ | bash

      - name: Run tests
        run: arcium test
